package com.sameerasw.essentials.domain.genai

import androidx.annotation.Keep
import com.google.mlkit.genai.schema.annotations.Generable
import com.google.mlkit.genai.schema.annotations.Guide


@Keep
@Generable("Structured output representing an automation suggestion generated by Gemini Nano")
data class AutomationSuggestion(
    @Guide(
        description = "Type of automation: TRIGGER, STATE, or APP",
        enumValues = ["TRIGGER", "STATE", "APP"]
    )
    val type: String = "TRIGGER",

    @Guide(description = "Human-readable suggested title for the automation")
    val title: String = "",

    @Guide(
        description = "Trigger type if automation is TRIGGER type",
        enumValues = [
            "ScreenOff",
            "ScreenOn",
            "DeviceUnlock",
            "ChargerConnected",
            "ChargerDisconnected",
            "Schedule",
            "BluetoothConnected",
            "BluetoothDisconnected",
            "WifiConnected",
            "WifiDisconnected"
        ]
    )
    val triggerType: String? = null,

    @Guide(
        description = "State type if automation is STATE type",
        enumValues = ["Charging", "ScreenOn", "TimePeriod"]
    )
    val stateType: String? = null,

    @Guide(
        description = "List of action names to execute",
        minItems = 1,
        maxItems = 5
    )
    val actionTypes: List<String> = emptyList(),

    @Guide(description = "Brief human-readable summary of what this automation will do")
    val explanation: String = ""
)
